<?php

namespace AppBundle\Repository;

/**
 * AnomaliesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AnomaliesRepository extends \Doctrine\ORM\EntityRepository
{
}
