<?php

namespace AppBundle\Repository;

/**
 * AutreActiviteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AutreActiviteRepository extends \Doctrine\ORM\EntityRepository
{
}
