<?php

namespace AppBundle\Repository;

/**
 * AutreActiviteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AutreActiviteRepository extends \Doctrine\ORM\EntityRepository
{
    /*
     * FONCTION : Récupère toutes les autres activités entre 2 dates
     */
    public function findAutreActiviteCreatedBetweenTwoDates(\DateTime $date_debut, \DateTime $date_fin)
    {
        return $this->createQueryBuilder('m')
                    ->where("m.date > ?1")
                    ->andWhere("m.date < ?2")
                    ->orderBy('m.activite', 'ASC')
                    ->setParameter(1, $date_debut)
                    ->setParameter(2, $date_fin)
                    ->getQuery()
                    ->getResult();
    }
}
