<?php

namespace AppBundle\Repository;

/**
 * DonneeClientRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DonneeClientRepository extends \Doctrine\ORM\EntityRepository
{
}
