<?php

namespace AppBundle\Repository;

/**
 * DonneeClientElementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DonneeClientElementRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllByIdParent($id)
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT p FROM AppBundle:DonneeClientElement p
                  WHERE p.interaction = :id'
            )->setParameter('id',$id)
            ->getResult();
    }
}
