<?php

namespace AppBundle\Repository;

/**
 * DonneeClientElementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DonneeClientElementRepository extends \Doctrine\ORM\EntityRepository
{
}
