<?php

namespace AppBundle\Repository;

/**
 * ElementsValorisesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ElementsValorisesRepository extends \Doctrine\ORM\EntityRepository
{
}
