<?php

namespace AppBundle\Repository;

/**
 * GroupeDonneeClientRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GroupeDonneeClientRepository extends \Doctrine\ORM\EntityRepository
{
}
