<?php

namespace AppBundle\Repository;

/**
 * ListeElementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ListeElementRepository extends \Doctrine\ORM\EntityRepository
{
}
