<?php

namespace AppBundle\Repository;

/**
 * TypeHoraireRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeHoraireRepository extends \Doctrine\ORM\EntityRepository
{
}
