<?php

namespace AppBundle\Repository;

/**
 * TypeDonneeClientRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeDonneeClientRepository extends \Doctrine\ORM\EntityRepository
{
}
