<?php

namespace AppBundle\Repository;

/**
 * TypeActiviteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeActiviteRepository extends \Doctrine\ORM\EntityRepository
{
}
