<?php

namespace AppBundle\Repository;

/**
 * TypeElementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeElementRepository extends \Doctrine\ORM\EntityRepository
{
}
