<?php

namespace AppBundle\Repository;

/**
 * VentilationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VentilationRepository extends \Doctrine\ORM\EntityRepository
{
    /*
     * FONCTION : Récupère toutes les ventilations entre 2 dates
     */
    public function findVentilationCreatedBetweenTwoDates(\DateTime $date_debut, \DateTime $date_fin)
    {
        return $this->createQueryBuilder('m')
                    ->join('m.ventilationFormulaire', 'vf')
                    ->join('vf.formulaire', 'f')
                    ->where("m.dateSaisie > ?1")
                    ->andWhere("m.dateSaisie < ?2")
                    ->orderBy('f.libelle', 'ASC')
                    ->setParameter(1, $date_debut)
                    ->setParameter(2, $date_fin)
                    ->getQuery()
                    ->getResult();
    }

    /*
     * FONCTION :
     */
    public function findAllTempsPasseeVentilation($user,$id)
    {

        $dateless = new \DateTime("-1 day");
        $datemore = new \DateTime("+1 day");


        return $this->createQueryBuilder('t')
            ->join("t.formulaire", "f")
            ->where("t.formulaire = f.id" )
            ->where("t.utilisateur = ?1")
            ->andWhere("t.dateSaisie > ?2")
            ->andWhere("t.dateSaisie < ?3")
            ->andWhere("f.type_activite = ?4")
            ->setParameter(1, $user->getId())
            ->setParameter(2, $dateless)
            ->setParameter(3, $datemore)
            ->setParameter(4, $id)
            ->getQuery()
            ->getResult();
    }
}
