<?php

namespace AppBundle\Repository;

/**
 * VentilationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VentilationRepository extends \Doctrine\ORM\EntityRepository
{
}
