<?php

namespace AppBundle\Repository;

/**
 * VentilationFormulaireRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VentilationFormulaireRepository extends \Doctrine\ORM\EntityRepository
{
}
