<?php

namespace AppBundle\Repository;

/**
 * VentilationActiviteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VentilationActiviteRepository extends \Doctrine\ORM\EntityRepository
{
}
